"""add_knowledge_base_documents_table

Revision ID: 1514387c3691
Revises: d98834d8cd12
Create Date: 2025-12-19 17:10:26.609356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1514387c3691'
down_revision = 'd98834d8cd12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('framework_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('ISO', 'NIST', 'CUSTOM', name='knowledgesourcetype'), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['frameworks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_documents_framework_id'), 'knowledge_base_documents', ['framework_id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_documents_id'), 'knowledge_base_documents', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_documents_title'), 'knowledge_base_documents', ['title'], unique=False)
    op.create_table('gap_analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.Integer(), nullable=False),
    sa.Column('framework_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('GAP', 'COMPLIANT', 'ERROR', name='gapanalysisstatus'), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('policy_similarity', sa.Float(), nullable=True),
    sa.Column('kb_similarity', sa.Float(), nullable=True),
    sa.Column('coverage_level', sa.String(length=50), nullable=True),
    sa.Column('missing_requirements', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['framework_id'], ['frameworks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gap_analysis_control_company', 'gap_analysis_results', ['control_id', 'company_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_gap_analysis_results_company_id'), 'gap_analysis_results', ['company_id'], unique=False)
    op.create_index(op.f('ix_gap_analysis_results_control_id'), 'gap_analysis_results', ['control_id'], unique=False)
    op.create_index(op.f('ix_gap_analysis_results_framework_id'), 'gap_analysis_results', ['framework_id'], unique=False)
    op.create_index(op.f('ix_gap_analysis_results_id'), 'gap_analysis_results', ['id'], unique=False)
    op.drop_index(op.f('ix_framework_selections_id'), table_name='framework_selections')
    op.drop_table('framework_selections')
    op.alter_column('control_selections', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('control_selections', 'framework_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_control_selections_company_framework'), table_name='control_selections')
    # Skip status column change - keep existing enum type
    # op.alter_column('policies', 'status',
    #            existing_type=postgresql.ENUM('DRAFT', 'UNDER_REVIEW', 'APPROVED', 'PUBLISHED', 'ARCHIVED', 'rejected', name='policystatus'),
    #            type_=sa.String(length=50),
    #            existing_nullable=False)
    op.drop_index(op.f('ix_policies_company_id'), table_name='policies')
    op.drop_constraint(op.f('policies_company_id_fkey'), 'policies', type_='foreignkey')
    op.drop_column('policies', 'company_id')
    op.drop_column('policies', 'mapped_control_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policies', sa.Column('mapped_control_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('policies', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('policies_company_id_fkey'), 'policies', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_policies_company_id'), 'policies', ['company_id'], unique=False)
    op.alter_column('policies', 'status',
               existing_type=app.models.policy.PolicyStatusType(length=50),
               type_=postgresql.ENUM('DRAFT', 'UNDER_REVIEW', 'APPROVED', 'PUBLISHED', 'ARCHIVED', 'rejected', name='policystatus'),
               existing_nullable=False)
    op.create_index(op.f('ix_control_selections_company_framework'), 'control_selections', ['company_id', 'framework_id'], unique=False)
    op.alter_column('control_selections', 'framework_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('control_selections', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('framework_selections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('selected_framework_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('framework_selections_company_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('framework_selections_pkey')),
    sa.UniqueConstraint('company_id', name=op.f('framework_selections_company_id_key'))
    )
    op.create_index(op.f('ix_framework_selections_id'), 'framework_selections', ['id'], unique=False)
    # Skip status column change in downgrade
    # op.alter_column('policies', 'status',
    #            existing_type=sa.String(length=50),
    #            type_=postgresql.ENUM('DRAFT', 'UNDER_REVIEW', 'APPROVED', 'PUBLISHED', 'ARCHIVED', 'rejected', name='policystatus'),
    #            existing_nullable=False)
    op.drop_index(op.f('ix_gap_analysis_results_id'), table_name='gap_analysis_results')
    op.drop_index(op.f('ix_gap_analysis_results_framework_id'), table_name='gap_analysis_results')
    op.drop_index(op.f('ix_gap_analysis_results_control_id'), table_name='gap_analysis_results')
    op.drop_index(op.f('ix_gap_analysis_results_company_id'), table_name='gap_analysis_results')
    op.drop_index('idx_gap_analysis_control_company', table_name='gap_analysis_results')
    op.drop_table('gap_analysis_results')
    op.drop_index(op.f('ix_knowledge_base_documents_title'), table_name='knowledge_base_documents')
    op.drop_index(op.f('ix_knowledge_base_documents_id'), table_name='knowledge_base_documents')
    op.drop_index(op.f('ix_knowledge_base_documents_framework_id'), table_name='knowledge_base_documents')
    op.drop_table('knowledge_base_documents')
    # ### end Alembic commands ###
