"""create control selections table

Revision ID: 204a3c7007a2
Revises: cbe99a053972
Create Date: 2025-12-10 16:41:59.939891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '204a3c7007a2'
down_revision = 'cbe99a053972'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('framework_id', sa.Integer(), nullable=True),
    sa.Column('selected_control_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['framework_id'], ['frameworks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_selections_id'), 'control_selections', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_control_selections_id'), table_name='control_selections')
    op.drop_table('control_selections')
    # ### end Alembic commands ###
