"""add framework_selections and update policies with company_id and mapped_control_ids

Revision ID: d98834d8cd12
Revises: 204a3c7007a2
Create Date: 2025-12-10 17:18:14.803478

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd98834d8cd12'
down_revision = '204a3c7007a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('framework_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('selected_framework_ids', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    op.create_index(op.f('ix_framework_selections_id'), 'framework_selections', ['id'], unique=False)
    op.alter_column('control_selections', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('control_selections', 'framework_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('policies', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('policies', sa.Column('mapped_control_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_policies_company_id'), 'policies', ['company_id'], unique=False)
    op.create_foreign_key(None, 'policies', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'policies', type_='foreignkey')
    op.drop_index(op.f('ix_policies_company_id'), table_name='policies')
    op.drop_column('policies', 'mapped_control_ids')
    op.drop_column('policies', 'company_id')
    op.alter_column('control_selections', 'framework_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('control_selections', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_framework_selections_id'), table_name='framework_selections')
    op.drop_table('framework_selections')
    # ### end Alembic commands ###
